

.PHONY : TARGET0
TARGET0 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/add-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/add-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/add-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET1
TARGET1 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/addi-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/addi-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/addi-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET2
TARGET2 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/and-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/and-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/and-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET3
TARGET3 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/andi-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/andi-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/andi-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET4
TARGET4 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/auipc-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/auipc-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/auipc-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET5
TARGET5 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/beq-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/beq-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/beq-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET6
TARGET6 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bge-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bge-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bge-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET7
TARGET7 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bgeu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bgeu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bgeu-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET8
TARGET8 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/blt-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/blt-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/blt-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET9
TARGET9 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bltu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bltu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bltu-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET10
TARGET10 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bne-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bne-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/bne-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET11
TARGET11 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/fence-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/fence-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/fence-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET12
TARGET12 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/jal-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jal-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/jal-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET13
TARGET13 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/jalr-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jalr-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/jalr-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET14
TARGET14 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lb-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lb-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lb-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET15
TARGET15 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lbu-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lbu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lbu-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET16
TARGET16 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lh-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lh-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lh-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET17
TARGET17 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lhu-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lhu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lhu-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET18
TARGET18 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lui-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lui-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lui-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET19
TARGET19 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lw-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lw-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/lw-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET20
TARGET20 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/misalign1-jalr-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/misalign1-jalr-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/misalign1-jalr-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET21
TARGET21 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/or-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/or-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/or-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET22
TARGET22 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/ori-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/ori-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/ori-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET23
TARGET23 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sb-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sb-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sb-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET24
TARGET24 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sh-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sh-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sh-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET25
TARGET25 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sll-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sll-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sll-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET26
TARGET26 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/slli-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slli-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/slli-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET27
TARGET27 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/slt-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slt-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/slt-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET28
TARGET28 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/slti-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slti-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/slti-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET29
TARGET29 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sltiu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltiu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sltiu-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET30
TARGET30 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sltu-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sltu-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET31
TARGET31 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sra-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sra-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sra-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET32
TARGET32 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/srai-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srai-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/srai-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET33
TARGET33 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/srl-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srl-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/srl-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET34
TARGET34 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/srli-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srli-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/srli-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET35
TARGET35 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sub-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sub-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sub-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET36
TARGET36 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sw-align-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sw-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/sw-align-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET37
TARGET37 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/xor-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xor-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/xor-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;

.PHONY : TARGET38
TARGET38 :
	@cd /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/xori-01.S/dut; riscv32-unknown-elf-gcc -march=rv32i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/lovis/Klaw_CORE/riscof/projet/env/link.ld         -I /home/lovis/Klaw_CORE/riscof/projet/env/         -I /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/env /home/lovis/Klaw_CORE/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xori-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=32 -mabi=ilp32 ; /home/lovis/Klaw_CORE/riscof/../obj_dir/Vcore my.elf --riscof /home/lovis/Klaw_CORE/riscof/riscof_work/rv32i_m/I/src/xori-01.S/dut/DUT-projet.signature  >/dev/null 2>&1;