set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/lovis12/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/lovis12/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/core"
set ::env(RUN_LINTER) "0"
set ::env(DESIGN_NAME) "core"
set ::env(VERILOG_FILES) "/openlane/designs/core/src/bu.v /openlane/designs/core/src/rf.v /openlane/designs/core/src/core.v /openlane/designs/core/src/dec.v /openlane/designs/core/src/decoder.v /openlane/designs/core/src/lsu.v /openlane/designs/core/src/shifter.v /openlane/designs/core/src/exe.v /openlane/designs/core/src/ifetch.v /openlane/designs/core/src/alu.v"
set ::env(CLOCK_PERIOD) "10"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_NET) "clk"
set ::env(FP_PDN_VOFFSET) "7"
set ::env(FP_PDN_HOFFSET) "7"
set ::env(FP_PDN_SKIPTRIM) "1"
set ::env(FP_CORE_UTIL) "45"
