name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up tools
      run: |
        .github/workflows/scripts/setup.sh

    - name: Compile RTL design
      run: make

    - name: Cleanup
      run: make clean
